spring.application.name=database
# and of course you can add specefic connectiont to connect to database here as well
# For this section we learn about H2 and In-Memory connection and why it was helpful
# Check out my notes for more detail.