spring.application.name=database
spring.datasource.url=jdbc:mysql://localhost:5432/springdb
spring.datasource.username=springuser
spring.datasource.password=springpass
# The property below says: We always want to run schema and data .sql files
spring.sql.init.mode=always