spring.application.name=database
spring.datasource.url=jdbc:mysql://localhost:3306/springdb
spring.datasource.username=root
spring.datasource.password=password

# Hibernate sets up the schema file for us by using the entities we created
spring.jpa.hibernate.ddl-auto=update